
export const bookingData = [
  {
    username: "Bluenose",
    img: "../assets/image 12.png",
    status: "Pending",
    start_date: "10/01/24",
    end_date: "15/12/2021",
    suite: 1,
    room: null,
    id: 1,
  },
  {
    username: "alaa",
    img: "../assets/image 12.png",
    status: "Pending",
    start_date: "10/01/24",
    end_date: "15/12/2021",
    suite: 1,
    room: null,
    id: 100,
  },
  {
    username: "Bluenose",
    img: "../assets/Ellipse 3.png",
    status: "Done",
    start_date: "10/01/24",
    end_date: "15/12/2021",
    suite: null,
    room: 2,
    id: 2,
  },
  {
    username: "Bluenose",
    img: "../assets/Ellipse 3.png",
    status: "Cancel",
    start_date: "12/12/2021",
    end_date: "15/12/2021",
    suite: null,
    room: 3,
    id: 3,
  },
  {
    username: "Bluenose",
    img: "../assets/Ellipse 3.png",
    status: "Unverified",
    start_date: null,
    end_date: null,
    suite: 11,
    room: null,
    id: 4,
  },
  {
    username: "Bluenose",
    img: "../assets/Ellipse 3.png",
    status: "Cancel",
    start_date: "12/12/2021",
    end_date: "15/12/2021",
    suite: null,
    room: 12,
    id: 5,
  },
  {
    username: "Bluenose",
    img: "../assets/image 12.png",
    status: "Pending",
    start_date: "12/12/2021",
    end_date: "15/12/2021",
    suite: 1,
    room: null,
    id: 6,
  },
  {
    username: "Bluenose",
    img: "../assets/image 12.png",
    status: "Done",
    start_date: "12/12/2021",
    end_date: "15/12/2021",
    suite: 1,
    room: null,
    id: 7,
  },
  {
    username: "Bluenose",
    img: "../assets/image 12.png",
    status: "Pending",
    start_date: "12/12/2021",
    end_date: "15/12/2021",
    suite: 1,
    room: null,
    id: 8,
  },
  {
    username: "Bluenose",
    img: "../assets/image 12.png",
    status: "Done",
    start_date: "12/12/2021",
    end_date: "15/12/2021",
    suite: 1,
    room: null,
    id: 8,
  },
  {
    username: "Bluenose",
    img: "../assets/image 12.png",
    status: "Pending",
    start_date: "12/12/2021",
    end_date: "15/12/2021",
    suite: 1,
    room: null,
    id: 8,
  },
  {
    username: "Bluenose",
    img: "../assets/image 12.png",
    status: "Done",
    start_date: "12/12/2021",
    end_date: "15/12/2021",
    suite: 1,
    room: null,
    id: 8,
  },
  {
    username: "Bluenose",
    img: "../assets/image 12.png",
    status: "Done",
    start_date: "12/12/2021",
    end_date: "15/12/2021",
    suite: 1,
    room: null,
    id: 8,
  },
  {
    username: "Bluenose",
    img: "../assets/image 12.png",
    status: "Done",
    start_date: "12/12/2021",
    end_date: "15/12/2021",
    suite: 1,
    room: null,
    id: 8,
  },
  {
    username: "Bluenose",
    img: "../assets/image 12.png",
    status: "Done",
    start_date: "12/12/2021",
    end_date: "15/12/2021",
    suite: 1,
    room: null,
    id: 8,
  },
  {
    username: "Bluenose",
    img: "../assets/image 12.png",
    status: "Done",
    start_date: "12/12/2021",
    end_date: "15/12/2021",
    suite: 1,
    room: null,
    id: 8,
  },
];

export const usersData = [
  {
    id: 1,
    img:  "../public/assets/image 12.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 2,
    img:  "../public/assets/image 12.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 3,
    img:  "../public/assets/image 12.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 4,
    img:  "../public/assets/image 12.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 5,
    img:  "../public/assets/image 12.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 6,
    img:  "../public/assets/image 12.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 7,
    img: "../public/assets/Ellipse 3.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 8,
    img: "../public/assets/Ellipse 3.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 9,
    img: "../public/assets/Ellipse 3.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 9,
    img: "../public/assets/Ellipse 3.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 9,
    img: "../public/assets/Ellipse 3.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 9,
    img: "../public/assets/Ellipse 3.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 9,
    img: "../public/assets/Ellipse 3.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 9,
    img: "../public/assets/Ellipse 3.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
  {
    id: 9,
    img: "../public/assets/Ellipse 3.png",
    username: "Bluenose",
    date: "10/01/24",
    delete: "../public/assets/cancel-01.svg",
  },
];

export const roomsData = [
  {
    id: 1,
    room: 1,
    suite: null,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
  },
 
  {
    id: 2,
    room: null,
    suite: 1,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
    },
  {
    id: 1,
    room: 1,
    suite: null,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
  },
 
  {
    id: 2,
    room: null,
    suite: 1,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
    },
  {
    id: 1,
    room: 1,
    suite: null,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
  },
 
  {
    id: 2,
    room: null,
    suite: 1,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
    },
  {
    id: 1,
    room: 1,
    suite: null,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
  },
 
  {
    id: 2,
    room: null,
    suite: 1,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
    },
  {
    id: 1,
    room: 1,
    suite: null,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
  },
 
  {
    id: 2,
    room: null,
    suite: 1,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
    },
  {
    id: 1,
    room: 1,
    suite: null,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
  },
 
  {
    id: 2,
    room: null,
    suite: 1,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
    },
  {
    id: 1,
    room: 1,
    suite: null,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
  },
 
  {
    id: 2,
    room: null,
    suite: 1,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
    },
  {
    id: 1,
    room: 1,
    suite: null,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
  },
 
  {
    id: 2,
    room: null,
    suite: 1,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
    },
  {
    id: 1,
    room: 3,
    suite: null,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
  },
 
  {
    id: 2,
    room: null,
    suite: 1,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
    },
  {
    id: 1,
    room: 1,
    suite: null,    
    beds: "Single Bed",
    persons: "1 Person",
    status: "Available",
  },
 
];
